### PR TITLE
Lab3

### PR DESCRIPTION
**Pull request by marina01p**
For lab 3:
- Integrate data from an API
- Add one more screen to have 5
- Add design to the application

For lab 4:
- Trying to create an MVP arhitecture

### CODE REVIEW

**Comment by marina01p** [comment]
Here, I added lab 4 as well, since I forgot to create a new new brach for it. Sorry!

**Review by ASV44 — CHANGES_REQUESTED** [review]
@marina01p please create branch for lab 4 from this branch. After that remove all commits related to LAB 4 from this branch and open PR for LAB 4

**Review by ASV44 — CHANGES_REQUESTED** [review]
@marina01p I observed that you implemented bottom navigation using activities, that is not right way of implementing it.
Please refactor bottom navigation to use fragments. You can find example how to do this in my [sample android app](https://github.com/ASV44/sample-android-app)

**Comment by marina01p** [comment]
But this means that I have to change all my activities to fragments, as I have the navigation bar for all of them.
Can I use instead the drawer menu for activities (as shown in your example with Expenses Activity)?

**Comment by ASV44** [comment]
> But this means that I have to change all my activities to fragments, as I have the navigation bar for all of them.
> Can I use instead the drawer menu for activities (as shown in your example with Expenses Activity)?

@marina01p Yes you can remove bottom bar navigation and use in stead drawer navigation with activities. But not both

**Comment by marina01p** [comment]
I added a drawer menu instead of bottom bar navigation.

**Review by ASV44 — APPROVED** [review]
@marina01p PR approved. Please merge it and rebase PR #4 on top of it after merge

**Pull request merged**
